# Generated by Django 5.2 on 2025-04-04 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('head_of_family', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Purok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('sex', models.CharField(max_length=10)),
                ('civil_status', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='residents.household')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='residents.purok')),
            ],
        ),
        migrations.AddField(
            model_name='household',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='households', to='residents.street'),
        ),
    ]
