# Generated by Django 5.2 on 2025-05-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='resident',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='resident',
            name='occupation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='sex',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='street',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
